vault-ui/src/components/Title.tsx, vault-ui/src/pages/login/AuthenticateAnotherWayPage.tsx, vault-ui/src/pages/login/ChooseOrganizationPage.tsx, vault-ui/src/pages/login/CreateOrganizationPage.tsx, vault-ui/src/pages/login/ForgotPasswordPage.tsx, vault-ui/src/pages/login/LoginPage.tsx, vault-ui/src/pages/login/RegisterAuthenticatorAppPage.tsx, vault-ui/src/pages/login/RegisterPasskeyPage.tsx, vault-ui/src/pages/login/RegisterPasswordPage.tsx, vault-ui/src/pages/login/RegisterSecondaryFactorPage.tsx, vault-ui/src/pages/login/SignupPage.tsx, vault-ui/src/pages/login/VerifyAuthenticatorAppPage.tsx, vault-ui/src/pages/login/VerifyAuthenticatorAppRecoveryCodePage.tsx, vault-ui/src/pages/login/VerifyEmailPage.tsx, vault-ui/src/pages/login/VerifyPasskeyPage.tsx, vault-ui/src/pages/login/VerifyPasswordPage.tsx, vault-ui/src/pages/login/VerifySecondaryFactorPage.tsx
This PR adds `Title` components to the vault login pages. It also fixes the `Title` component to not include `Tesseral` in vault titles.
=> [OPEN-349] Add titles to vault login pages

console/src/pages/project/project-ui-settings/ProjectUISettings.tsx
This PR adds secondary state for `lastValidPrimaryColor` and `lastValidDarkModePrimaryColor` to prevent re-renders with invalid hex values.
It also adds `handlePrimaryColorChange` and `handleDarkModePrimaryColorChange` to do hex checks on the color values on blur.
=> [OPEN-351] Fix color picker crashes

console/package-lock.json, console/package.json, console/src/pages/login/AuthenticateAnotherWayPage.tsx, console/src/pages/login/VerifyEmailPage.tsx, vault-ui/src/pages/login/AuthenticateAnotherWayPage.tsx, vault-ui/src/pages/login/VerifyEmailPage.tsx
This PR adds support for log in with email in the "authenticate another way" flow.
To prevent invalid redirects after email verification, it updates the redirect logic to use the `useRedirectNextLoginFlowPage` function instead of a hard-coded link to `/choose-organization`.
Email login tested locally in vault and console for both initial email login and "authenticate another way" email login.
I also updated the `react-hook-form` package to fix the gross typing issues they had in their previous version.
=> [OPEN-347] Add authenticate another way email support to console and vault

cmd/openauthctl/migrations/000069_email_quotas.up.sql, internal/backend/store/queries/models.go, internal/backend/store/queries/queries-backend.sql.go, internal/common/store/queries/models.go, internal/configapi/store/queries/models.go, internal/frontend/store/queries/models.go, internal/frontend/store/queries/queries-frontend.sql.go, internal/intermediate/store/email_verification_challenges.go, internal/intermediate/store/passwords.go, internal/intermediate/store/queries/models.go, internal/intermediate/store/queries/queries-intermediate.sql.go, internal/saml/store/queries/models.go, internal/saml/store/queries/queries-saml.sql.go, internal/scim/store/queries/models.go, internal/store/queries/models.go, internal/store/queries/queries.sql.go, internal/wellknown/store/queries/models.go, sqlc/queries-intermediate.sql
These quotas can be modified per-project, with a global default.
As a demo of this limit being implemented in staging, if a project is in the state where their limit is 100 per day, and they've already consumed that limit:
```
tesseraldb=> select * from project_email_quota_daily_usage ;
project_id              |    date    | quota_usage 
--------------------------------------+------------+-------------
be647431-a850-47e7-942c-c6041101233a | 2025-04-11 |         100
(1 row)
```
Then attempting to "Resend verification link" results in:
```
{
"code": "failed_precondition",
"message": "failed_precondition",
"details": [
{
"type": "tesseral.common.v1.ErrorDetail",
"value": "ChplbWFpbCBkYWlseSBxdW90YSBleGNlZWRlZA",
"debug": {
"description": "email daily quota exceeded"
}
}
]
}
```
=> [OPEN-345] Implement daily quotas on transactional emails per project

console/src/pages/organizations/ListOrganizationsPage.tsx, console/src/pages/organizations/OrganizationUsersTab.tsx, internal/backend/store/organizations.go
This PR adds support for creating Organizations and Users from the console. Given the restrictions of the types of Organizations that can be associated with the Dogfood Project, there is also a check added to the `CreateOrganization` function in the backend store to prevent this RPC from being run on the Dogfood Project.
=> [OPEN-346] Create Users and Organizations from the console

cmd/api/main.go, docker-compose.yaml
This PR removes the `depends_on` from nginx in docker-compose to prevent crashes when the api auto-rebuilds.
It also removes the db ping from the `api` startup.
=> Prevent nginx from crashing locally

console/src/App.tsx, console/src/lib/AccessTokenProvider.tsx
This PR resolves issues with cookie management in React (the same issue we saw with [the SDK](https://github.com/tesseral-labs/tesseral-sdk-react/pull/4)). We're now holding returned access tokens in memory to get around the unreliability of document.cookie in the React lifecycle.
There was also an issue with some of the `App.tsx` imports and routes since Google and Microsoft settings are in modals now, so I resolved those to get the local build working.
=> [OPEN-362] Resolve React cookie management issues

console/src/pages/home/HomePage.tsx
This PR updates the console home page to include a Growth Tier upgrade CTA for projects that are not on Growth or higher.
=> [OPEN-378] Add upgrade CTA to home page

internal/saml/service/service.go
This is a regression introduced by changes to our load balancer setup. In the interest of keeping things simple, this PR has us explicitly set the content-type of the SAML init endpoint.
=> saml: init: set text/html as content-type

console/src/App.tsx, console/src/components/ConsoleNavigation.tsx, console/src/pages/api-keys/ViewBackendAPIKeyPage.tsx, console/src/pages/api-keys/ViewPublishableKeyPage.tsx, console/src/pages/project/ListAPIKeysTab.tsx, console/src/pages/project/ViewProjectSettingsPage.tsx
This PR fixes the API Key pages' discoverability within the console by moving the API Keys page to a tab in Project Settings.
To accommodate this change, a small exception was added to the navigation to exclude link creation for `publishable-keys` and `backend-api-keys`, since those routes don't exist independently.
=> [OPEN-403] Fix api keys pages

.local/nginx/default.conf, .local/nginx/includes/vault.conf
This PR makes changes only for local development. In particular, this PR changes how nginx configuration works in local dev:
1. All nginx server blocks that front other docker containers are configured with `resolver 127.0.0.11 valid=1s;` and do not directly `proxy_pass http://container;`, instead doing a `set $upstream http://container; proxy_pass $upstream;`. This has the effect of forcing nginx to do DNS lookups at HTTP request time, and of re-resolving container addresses with a 1-second TTL. This TTL-ing is necessary because if the proxied container is restarted, it may be come back on a different IP address.
2. Most of the parameters we were passing to `proxy_pass` are unnecessary. Simple is easier to fix down the line. IPv6 configuration also got the same treatment.
3. I …
=> Simplify nginx configuration and force lazy DNS resolution

console/src/pages/organizations/api-keys/CreateAPIKeyButton.tsx, internal/backend/store/api_keys.go, internal/common/apierror/errors.go
This PR returns more meaningful responses from the ValidateAPIKey request when the API key is either malformed or otherwise invalid.
It also fixes a small import error with the Select menu for the `CreateAPIKeyButton` form.
=> Return more meaningful errors for failed ValidateAPIKey requests

console/src/pages/project/ProjectDetailsTab.tsx
Currently API Keys is showing twice on the ProjectDetailsTab of the console. This removes the duplicate.
=> Remove duplicate card on ProjectDetailsTab

internal/intermediate/store/exchange.go, internal/intermediate/store/queries/queries-intermediate.sql.go, sqlc/queries-intermediate.sql
When logging in with GitHub or some external IdP, any details captured on the intermediate session (like GitHub user ID, profile picture URL, etc) are not transferred to the user upon login.
Before, linking an existing account with a GitHub login would not populate the user's details like GitHub User ID:
Now, user details are populated on login:
=> Update user details on login

vault-ui/src/pages/dashboard/OrganizationUsersTab.tsx
For consistency with RPC calls and audit log event names. We'll reserve "revoke" for cases where there is an additional step to delete a resource, e.g. API keys.
=> Revoke -> Delete for user invites in Vault

cmd/openauthctl/migrations/000079_add_cascading_deletes.up.sql
This PR updates our db schema to include cascading deletes on all foreign key constraints to prevent random errors when deleting resources.
=> Add cascading deletes

internal/intermediate/store/email_verification_challenges.go
When copy/pasting an email verification challenge from an email, it is easy to accidentally include trailing spaces, which causes validation to fail on the backend. This commit trims the email verification challenges before verifying to prevent such issues.
Confirmed fix via manual testing.
=> Trim email verification challenges to avoid issues with trailing spaces

internal/backend/store/projects.go
Just a general good practice to save a few cycles and a pattern that's already used in other parts of the code:
```go
% grep -r "regexp.Must" .
./internal/scim/service/service.go:	filterEmailPat = regexp.MustCompile(`userName eq "(.*)"`)
./internal/backend/store/rbac_policies.go:var actionPattern = regexp.MustCompile(`^[a-z0-9_]+\.[a-z0-9_]+\.[a-z0-9_]+`)
./internal/backend/store/projects.go:	apiKeySecretTokenPrefixRegex = regexp.MustCompile(`^[a-z0-9_]+$`)
./internal/emailaddr/emailaddr.go:var pat = regexp.MustCompile(`^[a-zA-Z0-9_.\-\\#+]+@([a-zA-Z0-9_.-]+)$`)
```
=> chore: precompile API key secret token prefix regex

internal/backend/store/queries/queries-backend.sql.go, sqlc/queries-backend.sql
Currently, once an action is added to the RBAC policy, its description is effectively permanent.
The way that the current `UpsertAction` query works, it simply ignores description changes when performing the Upsert.
---
This PR updates the `UpsertAction` query in the backend service to update the description on conflicts, allowing for editing actions from the Console and API.
=> Allow editing of RBAC actions

internal/intermediate/store/queries/queries-intermediate.sql.go, sqlc/queries-intermediate.sql
If a Project has only "Log in with Password" enabled and an end user inputs an email/password pair matching a single user, but that user has no `password_bcrypt`, then the user receives an error about no password being registered.
This PR instead has our behavior be to fail to find a matching user for the flow, and to fall back to the Log in with Email flow.
=> Log in with Password: Only match users with `password_bcrypt`

internal/common/apierror/errors.go, internal/frontend/store/authenticator_apps.go, vault-ui/src/pages/dashboard/RegisterAuthenticatorAppButton.tsx
This PR improves the UX around authenticator app registration in the Vault. Spacing is fixed, a clear error state for bad TOTP codes, a success toast on completion of the flow, and reloading state after registering.
=> [OPEN-452] [OPEN-453] Fix authenticator app UI padding and error state

internal/backend/store/queries/queries-backend.sql.go, internal/frontend/store/queries/queries-frontend.sql.go, sqlc/queries-backend.sql, sqlc/queries-frontend.sql
The way that our page token logic works is that it encodes the next ID in a query as the pageToken in the response. This is used in our list queries (ordered by id) to `SELECT ... WHERE id >= @page_token`.
However, in some of our queries, we were selecting `WHERE id > @page_token`. This resulted in single records being dropped when paginating.
This PR updates these queries to select `WHERE id >= @page_token` instead.
=> Resolve issues with some list queries not selecting properly

internal/backend/store/queries/queries-backend.sql.go, internal/frontend/store/queries/queries-frontend.sql.go, sqlc/queries-backend.sql, sqlc/queries-frontend.sql
This is effectively the same fix as #470, but audit logs are sorted in the opposite direction, so this was missed when grepping for queries.
This PR updates the audit log queries to use `WHERE id <= @page_token` instead of `WHERE id < @page_token`.
=> Fix pagination for audit log queries

console/src/pages/console/settings/authentication/ManagedApiKeySettingsCard.tsx
When enabling Managed API Keys at the Project level, a secret token prefix is required. Currently the server fails if no secret token prefix is provided.
This PR also adds a client-side check to fail earlier if no secret token prefix is provided.
=> Enforce restrictions around secret tokens when apiKeysEnabled is true

console/src/pages/console/organizations/OrganizationAuthenticationTab.tsx
The rendering of Organization SAML settings in the console is currently conditionally rendering based on an Organization property instead of a Project property. This PR fixes the condition to use the correct Project property instead.
=> Fix logic for rendering SAML card

console/src/pages/console/settings/authentication/EnterpriseSettingsCard.tsx
Previously, clicking the "Save" button in the SAML settings dialog would not trigger the form submission, making the button non-functional.
=> Fix Console dialog for SAML settings

console/src/pages/console/organizations/authentication/OrganizationSamlCard.tsx
With the Console redesign, we missed the inclusion of organization domain settings. This PR adds this setting back in.
=> Add organization domains back to console

console/src/lib/access-token-provider.tsx, vault-ui/src/components/page/LoggedInGate.tsx
Currently, if pages are left idle on the console or vault, the access token becomes invalid and react query's automatic refetching will start to 401.
The vault is currently polling on a 60-second cadence, which can result in up to 50 seconds of expired access tokens. This PR updates both the vault and console to poll on a 2 second interval to check if refresh is required.
=> Add proactive access token refresh

cmd/openauthctl/migrations/000083_fix_email_quota_deletes.up.sql
Since there is no primary key on the `project_email_quota_daily_usage` table, cascading deletes break as there is no replica identity. Typically, with 1:1 tables (if we only had one record per project), we could just make the project ID the primary key.
Since this is not the case, we need to use the full record as the replica identity in order to postgres to be able to properly track cascading deletes.
This PR alters the table to include this replica identity.
=> Add replica identity to enable cascading deletes of email quota records

console/src/pages/login/VerifyPasskeyPage.tsx, internal/frontend/store/passkeys.go, internal/intermediate/store/passkeys.go
Currently, our Passkey Relying Party ID is operating on the assumptions built up by the Google and Safari implementation of domain restriction (which allow for subdomains of the current origin as a valid RP ID). However, their implementations stray a bit from [the spec itself](https://www.w3.org/TR/webauthn-2/#rp-id) which states that the RP ID `must be equal to the origin's effective domain, or a registrable domain suffix of the origin's effective domain`.
This PR updates our Passkey rpcs for issuing challenges and getting options for Passkey registration and verification in both the frontend and intermediate stores to use the Project's `cookie_domain` instead of the `vault_domain`. This loosely ensures stronger compatibility with the expectations of the spec (and solves some problems …
=> Fix passkeys

cmd/openauthctl/migrations/000084_audit_log_events_project_id.up.sql
Updates the `audit_log_events` table to allow the `project_id` column to be nullable, enabling the deletion of projects without affecting existing audit log events.
=> Allow deletion of projects

cmd/api/Dockerfile, console/Dockerfile, docker-compose.yaml, vault-ui/Dockerfile
Alpine is known to have a very slow memory allocator leading to longer iteration times when running locally
=> Migrate away from alpine

console/src/pages/console/settings/api-keys/publishable-keys/ListPublishableKeysCard.tsx
When selecting the "Development mode" checkbox, pass the `devMode` property to the backend API.
=> [OPEN-509] Allow creation of dev mode publishable keys

vault-ui/src/pages/vault/organization/scim-api-keys/ScimApiKeyPage.tsx, vault-ui/src/pages/vault/organization/scim-api-keys/ScimApiKeysCard.tsx
Looks like this was missed in the redesign. Currently, it's not possible to delete SCIM API keys without first revoking them, but this functionality was removed from the Vault.
Also fixes redirect post-deletion.
https://github.com/user-attachments/assets/1af546ae-515d-4d2a-9d85-71c7e549bf78
=> Add back revocation of SCIM API keys in Vault

vault-ui/src/pages/login/FinishLoginPage.tsx
In dev mode, when using hash, only include Tesseral parameters in the redirect hash. Currently, if the redirect URI has query parameters, they are included in the hash which breaks the dev mode callback logic in the React SDK.
=> Fix redirect URI handling in FinishLoginPage

console/src/pages/console/organizations/authentication/ListOrganizationOidcConnectionsCard.tsx, console/src/pages/console/organizations/authentication/ListOrganizationSamlConnectionsCard.tsx, vault-ui/src/pages/vault/organization/oidc-connections/OidcConnectionsCard.tsx, vault-ui/src/pages/vault/organization/saml-connections/SamlConnectionsCard.tsx
When creating SAML/OIDC connections in the vault or console, mark it primary if it is the first connection for that organization.
=> [OPEN-538] First SAML/OIDC connection should be primary

cmd/openauthctl/migrations/000085_oidc_connections_cascade_delete.up.sql, internal/backend/store/organizations_test.go
Miss from #489. I copied the original SAML connections migration without seeing the cascade deletes added in a subsequent migration.
=> Add cascade delete constraints to OIDC connections and intermediate sessions

vault-ui/src/pages/vault/user/UserDetailsTab.tsx
- Fixes bug where the Change Password button did nothing (moved the `DialogFooter` inside the `form` so that `type=submit` works).
- Removes double `FormMessage` elements
- Adds a confirm password field to the reset password dialog.
=> [OPEN-525] Better reset password dialog handling

vault-ui/src/components/saml-connections/SetupWizardVideo.tsx, vault-ui/src/components/saml-connections/entra/AssignEntraSamlUsers.tsx, vault-ui/src/components/saml-connections/entra/ConfigureEntraSamlIdentifier.tsx, vault-ui/src/components/saml-connections/entra/ConfigureEntraSamlReplyUrl.tsx, vault-ui/src/components/saml-connections/entra/CreateEntraSamlApplication.tsx, vault-ui/src/components/saml-connections/entra/DownloadEntraSamlMetadata.tsx, vault-ui/src/components/saml-connections/google/AssignGoogleSamlUsers.tsx, vault-ui/src/components/saml-connections/google/ConfigureGoogleSamlApplication.tsx, vault-ui/src/components/saml-connections/google/CreateGoogleSamlApplication.tsx, vault-ui/src/components/saml-connections/google/DownloadGoogleSamlMetadata.tsx, vault-ui/src/components/saml-connections/google/NameGoogleSamlApplication.tsx, vault-ui/src/components/saml-connections/okta/AssignOktaSamlUsers.tsx, vault-ui/src/components/saml-connections/okta/ConfigureOktaSamlApplication.tsx, vault-ui/src/components/saml-connections/okta/CreateOktaSamlApplication.tsx, vault-ui/src/components/saml-connections/okta/NameOktaSamlApplication.tsx, vault-ui/src/components/saml-connections/okta/SyncOktaSamlMetadata.tsx
Uses the `Skeleton` component to display a loading tile for SAML Setup Wizard videos.
Shown here with artificial delay:
https://github.com/user-attachments/assets/ed866f42-12df-441e-a194-d00ed31034ed
=> [OPEN-512] Video fallback for SAML setup wizard

vault-ui/src/pages/login/LoginPage.tsx
(The point of the screenshot is that there's nothing there below the card.)
=> No "signup" subtitle if self-serve user creation disabled

cmd/api/logger.go, cmd/api/main.go, internal/multislog/multislog.go
Even when OTEL logging is enabled, we want to ensure that logs are always output to stdout.
=> Always output logs to stdout

vault-ui/src/hooks/use-login-page-query-params.tsx, vault-ui/src/pages/login/FinishLoginPage.tsx, vault-ui/src/pages/login/LoginPage.tsx, vault-ui/src/pages/login/SignupPage.tsx
This PR moves the login flow's URL-supplied state (`relayed-session-state`, `redirect-uri`, and `return-relayed-session-token-as-query-param`) to persist in localstorage.
Today, this state is only loaded from the URL, but we also strip it from the URL upon loading it. That interacts poorly with browser history -- certain patterns of hitting back or refreshing can lose that state.
With this PR, this state continues to be accepted as a query parameter, but is persisted in local storage. Finishing a login resets the state.
=> [OPEN-606] Move Login flow query param state into localStorage

cmd/openauthctl/main.go, cmd/openauthctl/migrations/000092_project_logo_urls.up.sql, cmd/openauthctl/update_project.go, internal/auditlog/store/queries/models.go, internal/backend/store/project_ui_settings.go, internal/backend/store/queries/models.go, internal/backend/store/queries/queries-backend.sql.go, internal/common/store/queries/models.go, internal/configapi/store/queries/models.go, internal/defaultoauth/store/queries/models.go, internal/frontend/store/queries/models.go, internal/frontend/store/queries/queries-frontend.sql.go, internal/intermediate/store/queries/models.go, internal/intermediate/store/queries/queries-intermediate.sql.go, internal/intermediate/store/settings.go, internal/oidc/store/queries/models.go, internal/saml/store/queries/models.go, internal/scim/store/queries/models.go, internal/store/projects.go, internal/store/queries/models.go, internal/store/queries/queries.sql.go, sqlc/queries.sql
This PR adds an `update-project` command to the ctl tool, which allows self-hosters to directly control, through the database, a Project's Vault domain and logos. This allows self-hosters to conveniently bypass dependencies on S3 and Cloudflare.
For logos, a new set of columns for `logo_url` and `dark_mode_logo_url` take precedence over other settings. If enabled, these are unconditionally used as the hotlinkable URL to use for presentational purposes.
=> [OPEN-586] Add update-project ctl command + bypass s3 with direct urls

internal/backgroundworker/store/email.go
For consistency, this PR updates the `custom_email.verify_email` webhook payload to use the field `emailVerificationChallengeCode` (currently: `emailVerificationCode`). This is the more correct public-facing name for these codes.
```json
{
"emailAddress": "ulysse.carion@ssoready.com",
"emailVerificationChallengeCode": "email_verification_challenge_code_505d7k87168m6jg28vc6j20ix",
"type": "custom_email.verify_email"
}
```
=> Custom Emails: Fix verify_email payload field name

vault-ui/src/pages/login/LoginPage.tsx, vault-ui/src/pages/login/SignupPage.tsx
This PR makes improvements to the end user experience of logging in when SAML or OIDC are available:
1. The login page recalls the last used email, and uses that as a default for subsequent visits.
2. When SAML or OIDC connections are available, the login and signup page display that as the "primary" option. They have `type="submit"` and appear above email/password logins, which are now secondary options.
=> [OPEN-609] [OPEN-607] Vault: Recall last email, make SAML/OIDC "primary" in UI when available

.github/workflows/docker-images-stable.yml, .github/workflows/docker-images-unstable.yml
This PR adds tesseral-internal-api builds to the stable and unstable Docker channels.
=> [OPEN-605] Add tesseral-internal-api to docker image builds
