tesseral-labs/tesseral

cmd/api/main.go
internal/intermediate/store/settings.go
internal/intermediate/store/store.go

This fixes a broken img tag on fresh vaults.

[OPEN-354] vault: HeadObject logos to avoid returning nonexistent logo URL

---

console/src/pages/organizations/ViewOrganizationPage.tsx
console/src/pages/users/ViewUserPage.tsx

This PR adds support for editing Users and Organizations from the console.

[OPEN-356] Edit Organizations and Users

---

console/src/pages/project/project-ui-settings/ProjectUISettings.tsx

This PR fixes the color picker propagation into the vault ui preview within the vault ui settings.

[OPEN-364] Fix color picker propagation

---

vault-ui/src/pages/login/LoginPage.tsx
vault-ui/src/pages/login/SignupPage.tsx

[OPEN-389] Use ListSAMLOrganizations to offer SP-initiated SAML from Signup, Login

---

console/src/pages/organizations/EditOrganizationPage.tsx

Add GitHub setting in edit organizations console page

---

vault-ui/src/pages/login/SignupPage.tsx

Fix mobile signup styles

---

console/src/components/page.tsx

Fix console header z-index

---

vault-ui/src/App.tsx
vault-ui/src/pages/dashboard/OrganizationLoginSettingsTab.tsx
vault-ui/src/pages/dashboard/OrganizationSAMLConnectionsTab.tsx
vault-ui/src/pages/dashboard/OrganizationSettingsPage.tsx
vault-ui/src/pages/dashboard/saml-connections/CreateSAMLConnectionButton.tsx
vault-ui/src/pages/dashboard/saml-connections/ViewSAMLConnectionPage.tsx

This PR adds support for managing SAML connections in the vault. The tab for managing SAML connections is conditionally added based on the project and organization settings.

SAML Connections in Vault

---

console/src/pages/users/ViewUserPage.tsx

Ensure that GitHub user ID is populated and updated in the user edit screen.

Fix GitHub User ID in console

---

console/src/pages/organizations/OrganizationAPIKeysTab.tsx
vault-ui/src/pages/dashboard/APIKeysTab.tsx

Grep'd through for other places but these seem to be the only two instances.

Fix API Key revoked status in UI

---

internal/intermediate/store/exchange.go
vault-ui/src/pages/dashboard/AuditLogEventsPage.tsx

Fix filtering in Vault

---

README.md

- Add Rust SDK
- Add FastAPI SDK
- Update Next.js references

Update SDKs in README

---

console/src/pages/console/settings/vault/details/VaultBehaviorSettingsCard.tsx

The Console redesign did not include the UI for the Project-level setting for displaying (or not displaying) audit logs in the vault pages.
This PR adds this setting to the Console UI.

Add missing audit logs setting

---

internal/intermediate/store/impersonate.go

Don't capture intermediate session ID for user impersonation call since there is none available and attempting to capture it will lead to a panic.

Fix user impersonation audit log event

---

console/src/pages/console/organizations/OrganizationUsersTab.tsx

Fix GetOrganization call in console

---

console/src/pages/console/organizations/ListOrganizationsPage.tsx

This PR fixes a UI bug that causes strange dialog states when attempting to delete Organizations from the Organizations list in the Console.
https://github.com/user-attachments/assets/29dfdf2e-5648-4c14-be2e-5ea83bf26464

Fix UI bug when deleting organizations from list

---

console/src/pages/console/settings/vault/domains/VaultCookieDomainCard.tsx

Moves the FormField component within the Form component to avoid errors rendering the form.
Tested locally only.
https://github.com/user-attachments/assets/5a2905ae-db89-4fdf-a068-75e41635d303

[OPEN-511] Fix Vault Domain Cookie Domain Configuration

---

console/src/pages/console/organizations/api-keys/ListOrganizationApiKeysCard.tsx

This PR resolves an issue where the create api key flow was navigating away before the secret could be copied.

Fix create api key flow

---

console/src/pages/console/organizations/api-keys/ListOrganizationApiKeysCard.tsx

Fix API Key status

---

vault-ui/src/pages/vault/organization/oidc-connections/OidcConnectionPage.tsx
vault-ui/src/pages/vault/organization/saml-connections/SamlConnectionPage.tsx
vault-ui/src/pages/vault/organization/scim-api-keys/ScimApiKeyPage.tsx
vault-ui/src/pages/vault/user/UserDetailsTab.tsx

Improve Danger Zone UI for Dark Mode

---

vault-ui/src/pages/vault/AuditLogsPage.tsx

[OPEN-470] Fix vault audit log copy

---

internal/oidc/store/exchange.go

Fix after-login endpoint logic for OIDC exchange endpoint

---

console/src/pages/console/settings/authentication/EnterpriseSettingsCard.tsx
console/src/pages/console/settings/authentication/ManagedApiKeySettingsCard.tsx
console/src/pages/console/settings/vault/domains/VaultDomainsCard.tsx

Also adds toast notification for vault domain update

[OPEN-517] Updates dialogs to close after saving settings

---

vault-ui/src/pages/login/ImpersonatePage.tsx

[OPEN-570] Redirect to cookie domain after impersonation

---

console/build.mjs
console/src/App.tsx
console/src/config.ts
console/src/lib/AccessTokenProvider.tsx
console/src/lib/access-token-provider.tsx
console/src/lib/console-configuration.tsx

This PR adds the client-side implementation for Console Configuration discovery.
The server implementation is already released to production.
Tested on dev1.

[OPEN-573] Console Configuration Client

---

vault-ui/src/pages/login/LoginPage.tsx

This PR fixes a bug affecting Firefox. The native form functionality takes precedence over the button's handlers unless we call `preventDefault()`.

[OPEN-610] Fix login form submission errors in Firefox
